# kubectl apply -f deployment-3-configmaps+secrets.yml
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
#encoded of 2NZhAFU8kwwMdtvU
  password: Mk5aaEFGVThrd3dNZHR2VQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    create database profiles;
    CREATE USER empuser@'localhost' IDENTIFIED BY 'password';
    CREATE USER empuser@'%' IDENTIFIED BY 'password';
    ALTER USER 'empuser'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
    ALTER USER 'empuser'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
    GRANT ALL PRIVILEGES ON profiles.* to empuser@'localhost';
    GRANT ALL PRIVILEGES ON profiles.* to empuser@'%';