version: '3'
services:
  profiles:
    image: iyogi/profiles:milestone2
    ports:
      - "8080:8080"
    volumes:
      - /tmp/manning/profiles-app/images:/data
    networks:
      - appnet
    environment:
      - IMAGES_DIRECTORY=/data
    depends_on:
      - mysql

  mysql:
    image: "mysql:8"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    volumes:
      - /tmp/manning/profiles-app/data:/var/lib/mysql
      - ./src/docker/db:/docker-entrypoint-initdb.d
    networks:
      - appnet

networks:
  appnet:
    driver: bridge